version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=github_events
    restart: unless-stopped

  webhook-app:
    build: .
    container_name: webhook-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=github_events
      - COLLECTION_NAME=events
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-your_github_webhook_secret}
      - ADMIN_KEY=${ADMIN_KEY:-your_admin_key_here}
      - PORT=5000
    restart: unless-stopped

volumes:
  mongodb_data:
